hofvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    #dashboard
    path('dashboard',views.dashboard,name='dashboard'),
    #auth
    path('signup',views.SignUp.as_view(),name='signup'),
    path('login',auth_views.LoginView.as_view(),name='login'),
    path('logout',auth_views.LogoutView.as_view(),name='logout'),
    #halls
    path('halloffame/create',views.CreateHall.as_view(),name='create_hall'),
    path('halloffame/<int:pk>',views.DetailHall.as_view(),name='detail_hall'),
    path('halloffame/<int:pk>/update',views.UpdateHall.as_view(),name='update_hall'),
    path('halloffame/<int:pk>/delete',views.DeleteHall.as_view(),name='delete_hall'),
    #videos
    path('halloffame/<int:pk>/addvideo',views.add_video,name='add_video'),
    path('video/search',views.video_search,name='video_search'),
    path('video/<int:pk>/delete',views.DeleteVideo.as_view(),name='delete_video'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall,on_delete=models.CASCADE)

halls/forms.py
from .models import Video
from django import forms

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url':'YouTube Url'}

class SearchForm(forms.Form):
    search_form = forms.CharField(max_length=255, label='Search For Videos')

halls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from .models import Hall, Video
from .forms import VideoForm, SearchForm
from django.http import Http404, JsonResponse
import urllib
from django.forms.utils import ErrorList
import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
#from django.forms import formset_factory
# use this in add_video.html incase of formset{{ formset.management_form }}
# {{ for f in form }}   ....    {{ endfor }}

YOUTUBE_API_KEY = 'AIzaSyBGFHpvnRvKmFwZbQWW80elw5pUyZzy3_g'

# Create your views here.
def home(request):
    recent_halls = Hall.objects.all().order_by('-id')[:3]
    popular_halls = [Hall.objects.get(pk=1)]
    return render(request,'home.html',{'recent_halls':recent_halls,'popular_halls':popular_halls})

@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request,'dashboard.html',{'halls':halls})

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'

    def form_valid(self,form):
        view = super(SignUp,self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username,password=password)
        login(self.request,user)
        return view
# def create_hall(request):
#     if request.method == 'POST':
#         #get the form data
#         #validate form data
#         #create hall and save it
#     else:
#         #create a form for a hall
#         #return the template

class CreateHall(LoginRequiredMixin,generic.CreateView):
            model = Hall
            fields = ['title']
            template_name = 'create_hall.html'
            success_url = reverse_lazy('dashboard')

            def form_valid(self,form):
                form.instance.user = self.request.user
                super(CreateHall,self).form_valid(form)
                return redirect('dashboard')

class DetailHall(generic.DetailView):
    model = Hall
    template_name = 'detail_hall.html'

class UpdateHall(LoginRequiredMixin,generic.UpdateView):
    model = Hall
    template_name = 'update_hall.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateHall,self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

class DeleteHall(LoginRequiredMixin,generic.DeleteView):
    model = Hall
    template_name = 'delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall,self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

class DeleteVideo(LoginRequiredMixin,generic.DeleteView):
    model = Video
    template_name = 'delete_video.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo,self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video

@login_required
def add_video(request,pk):
    #VideoFormSet = formset_factory(VideoForm,extra=3)
    #form = VideoFormSet()
    form = VideoForm()
    searchform = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        #create
        form = VideoForm(request.POST)
        #filled_form = VideoFormSet(request.POST)
        if form.is_valid():
            #for form in filled_form:
            video = Video()
            video.hall = hall
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={ YOUTUBE_API_KEY }')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_hall',pk)
            else:
                errors = form._errors.setdefault('url',ErrorList())
                errors.append('Needs to be a YouTube URL')

    return render(request,'add_video.html',{'form':form,'search_form':searchform,'hall':hall})

def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_form'])
        response = requests.get(f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={ encoded_search_term }&key={ YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    return JsonResponse({'error':'No Results Found'})



# to seed data in json
# rm db.sqlite3
# python manage.py migrate
# python manage.py createsuperuser
# python manage.py dumpdata> seed_data.json
# python manage.py loaddata seed_data.json

halls/templates/add_video.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Add Video to {{ hall.title }}</h2>
  <form method="post" id="submit_video">
    <br />
    {% csrf_token %}
    {% load widget_tweaks %}
    {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      </div>
      {% endfor %}
    <button type="submit" class="btn btn-primary">Add</button>
    </form>
    <br />
    <h2>OR</h2>
    <form>
      {% for field in search_form %}
        {{ field.label_tag }}
        {% render_field field class="form-control" %}
        {% endfor %}
      </form>

      <div id="search_results"></div>
      <script>
        var delayTimer;
        $('#id_search_form').keyup(function() {
          clearTimeout(delayTimer);
          $('#search_results').text('Loading...');
          delayTimer = setTimeout(function() {
            var text = $('#id_search_form').val();
            $.ajax({
              url: '/video/search',
              data: {
                'search_form':text
              },
              dataType: 'json',
              success: function(data) {
                var results = '';
                $('#search_results').text('');

                results += '<div class="row">';

                data['items'].forEach(function(video) {
                  results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                  results += '<iframe width="335" height="240" src="https://www.youtube.com/embed/'+video['id']['videoId']+'" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
                  results += '<div class="card-body"><p class="card-text">'+video['snippet']['title']+'</p>';
                  results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' +video['id']['videoId']+ '\')">Add</a></div></div></div>';

                });
                results += '</div>';

                $('#search_results').append(results);
              }
            });
          },1000);
        });

        function addVideo(video_id) {
          $('#id_url').val('https://www.youtube.com/watch?v='+ video_id);
          $('#submit_video').submit();
        }
        </script>
    </div>
{% endblock %}

halls/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>hofvidz</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'original.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'original.ico' %}" />
</head>

    <body>
      <header>
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-dark border-bottom shadow-sm">
          <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-white">Hall of Fame Vidz</a></h5>
          <nav class="my-2 my-md-0 mr-md-3">
            {% if user.is_authenticated %}
            <a class="p-2 text-white" href="{% url 'dashboard' %}">Dashboard</a>
            <a class="p-2 text-white" href="{% url 'logout' %}">Log Out</a>
            {% else %}
            <a class="p-2 text-white" href="{% url 'login' %}">Log In</a>
            {% endif %}
          </nav>
          {% if user.is_authenticated == False %}
          <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
          {% endif %}
        </div>
  </header>
  <div class="container">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}
  </div>
</body>
<footer class="text-muted">
  <div class="container text-center">
      <p>©️ Aniket Anvekar </p>
  </div>
</footer>


</html>

halls/templates/create_hall.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Create a Hall Of Fame</h2>
  <form method="post">
    <br />
    {% csrf_token %}
    {% load widget_tweaks %}
    {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      </div>
      {% endfor %}
    <button type="submit" class="btn btn-primary">Create Hall</button>
    </form>
    </div>
{% endblock %}

halls/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="text-center">
    <h2>{{ user.username }}'s Hall of Fame</h2>
    <a href="{% url 'create_hall' %}" class="btn btn-primary">Create New Hall of Fame</a>
  </div>
    <br />
    {% for hall in halls %}
    <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
    <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete Hall</a>
    <a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Edit Hall</a>
    <a href="{% url 'add_video' hall.id  %}" class="btn btn-primary">Add Video</a>
    <div class="row">
    {% for video in hall.video_set.all %}
      <div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
      <iframe width="335" height="240" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <div class="card-body"><p class="card-text">{{ video.title }}</p>
      </div></div></div>
    {% endfor %}
    </div>
    {% endfor %}
{% endblock %}

halls/templates/delete_hall.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Delete this Hall Of Fame</h2>
  <br />
  <h4><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h4>
  <br />
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Move to trash</button>
    </form>
    </div>
{% endblock %}

halls/templates/delete_video.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Delete this Video</h2>
  <div class="row">
    <div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
    <iframe width="200" height="150" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="card-body"><p class="card-text">{{ video.title }}</p>
    </div></div></div>
  </div>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Delete</button>
    </form>
    </div>
{% endblock %}

halls/templates/detail_hall.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<h2>{{ hall.title }}</h2>
<h5 class="text-muted">Created By - {{ hall.user.username }}</h5>
{% if user.id == hall.user.id %}
<a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete Hall</a>
<a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Edit Hall</a>
<a href="{% url 'add_video' hall.id  %}" class="btn btn-primary">Add Video</a>
{% endif %}
<div class="row">
{% for video in hall.video_set.all %}
  <div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
  <iframe width="335" height="240" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <div class="card-body"><p class="card-text">{{ video.title }}</p>
    {% if user.id == hall.user.id %}
    <a href="{% url 'delete_video' video.id  %}" class="btn btn-primary">Delete</a>
    {% endif %}
  </div></div></div>
{% endfor %}
</div>
</div>
{% endblock %}

halls/templates/home.html
{% extends 'base.html' %}

{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">What's your personal Hall of Fame?</h1>
      <p>We are excited to know your all time favourite videos.You are just one click away to share it with the world.</p>
      {% if user.is_authenticated %}
        <a href="{% url 'create_hall' %}" class="btn btn-primary">Create Hall of Fame</a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-primary">Create Hall of Fame</a>
          {% endif %}
    </div>
    </section>
<div class="container">
  <h2 class="text-center">Popular Hall of Fames</h2>
  {% for hall in popular_halls %}
  <h4><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h4>
  <div class="row">
  {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
    <iframe width="335" height="240" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="card-body"><p class="card-text">{{ video.title }}</p>
    </div></div></div>
  {% endfor %}
  </div>
  {% endfor %}
  <h2 class="text-center">Recent Hall of Fames</h2>
  {% for hall in recent_halls %}
  <h4><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h4>
  <div class="row">
  {% for video in hall.video_set.all %}
    <div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
    <iframe width="335" height="240" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <div class="card-body"><p class="card-text">{{ video.title }}</p>
    </div></div></div>
  {% endfor %}
  </div>
  {% endfor %}
</div>

{% endblock %}

halls/templates/update_hall.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Create a Hall Of Fame</h2>
  <form method="post">
    <br />
    {% csrf_token %}
    {% load widget_tweaks %}
    {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{ field.errors }}
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      </div>
      {% endfor %}
    <button type="submit" class="btn btn-primary">Save</button>
    </form>
    <br />
    <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete Hall</a>
    </div>
{% endblock %}